version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - restore_cache:
          - key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - checkout
      - run:
          name: install dependencies
          command:
            python3 -m venv venv
            . venv/bin/activate
            sudo pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name : test
          command:
            . venv/bin/activate
            pytest live/client_test.py