version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command:
            pip install -r ../requirements.txt
      - run:
          command:
            pytest client_test.py